---
- name: Update system and install dependencies
  become: true
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - epel-release
    - nano

- name: Disable SELinux
  become: true
  replace:
    path: /etc/selinux/config
    regexp: 'SELINUX=permissive'
    replace: 'SELINUX=disable'

- name: Temporarily set SELinux to permissive
  become: true
  command: setenforce 0

- name: Download Prometheus Agent
  become: true
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: "/tmp/prometheusAgent.tar.gz"

- name: Extract Prometheus Agent
  ansible.builtin.unarchive:
    src: "/tmp/prometheusAgent.tar.gz"
    dest: "/tmp/"
    remote_src: yes
  become: true

- name: Move node_exporter binary to /usr/local/bin
  shell: "mv /tmp/node_exporter-*/node_exporter /usr/local/bin/node_exporter"
  args:
    executable: /bin/bash
  become: true


- name: Create Prometheus Agent user
  become: true
  user:
    name: "nodeusr"
    system: yes
    shell: "/bin/false"

- name: Copy systemd service file
  become: true
  copy:
    src: "{{ role_path }}/files/node_exporter.service"
    dest: "/etc/systemd/system/node_exporter.service"

- name: Reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: Enable and start Prometheus Agent service
  become: true
  systemd:
    name: "node_exporter"
    state: started
    enabled: yes

- name: Copy systemd service file
  become: true
  copy:
    src: "{{ role_path }}/files/daemon.json"
    dest: "/etc/docker/daemon.json"
  notify:
  - Restart Docker