- name: Copy Docker Compose file
  copy:
    src: "{{ role_path }}/files/docker-compose.yml"
    dest: ~/docker-compose.yaml

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: ~/provisioning/
    state: directory

- name: Copy Grafana conf file
  template:
    src: "{{ role_path }}/templates/datasource.yaml.j2"
    dest: ~/provisioning/datasource.yaml

- name: Start Loki with Docker Compose
  become_user: centos
  shell: |
    sudo /usr/local/bin/docker-compose up -d
