- name: Copy Docker Compose file
  copy:
    src: "{{ role_path }}/files/docker-compose.yml"
    dest: /home/centos/docker-compose.yaml

- name: Start Loki with Docker Compose
  become_user: centos
  shell: |
    cd /home/centos
    docker-compose up -d
