- name: Copy Docker Compose file
  copy:
    src: "{{ role_path }}/files/docker-compose.yml"
    dest: ~/docker-compose.yaml

- name: Create a datasources directory if it does not exist
  ansible.builtin.file:
    path: ~/provisioning/datasources
    state: directory

- name: Create a dashboard directory if it does not exist
  ansible.builtin.file:
    path: ~/provisioning/dashboards
    state: directory

- name: Copy Grafana dashboard provisioning file
  template:
    src: "{{ role_path }}/templates/datasource.yaml.j2"
    dest: ~/provisioning/datasources/datasource.yaml

- name: Copy Grafana dashboard provisioning file
  copy:
    src: "{{ role_path }}/files/dashboard.yaml"
    dest: ~/provisioning/dashboards/dashboard.yaml

- name: Copy Grafana dashboard file
  copy:
    src: "{{ role_path }}/files/AWS_Lambda.json"
    dest: ~/provisioning/dashboards/AWS_Lambda.json
#
- name: Start Loki with Docker Compose
  become_user: centos
  shell: |
    sudo /usr/local/bin/docker-compose up -d
