- name: Copy Docker Compose file
  copy:
    src: "{{ role_path }}/files/docker-compose.yml"
    dest: /home/centos/docker-compose.yaml

- name: Install Docker Compose
  become: true
  shell: |
    curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose


- name: Start Loki with Docker Compose
  command: "docker-compose up -d"
  args:
    chdir: /home/centos