#- name: Update yum cache
#  yum: 
#    name: '*'
#    state: present
#  become: true

- name: Install required software
  yum:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - httpd
    - mariadb-server
    - MySQL-python