# tasks file for server
- name: Update yum cache
  yum: 
    name: '*'
    state: present
  become: true

- name: Install required software
  yum:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - httpd
    - mariadb-server
    - MySQL-python

- name: Enable MariaDB service
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Enable httpd service
  systemd:
    name: httpd
    state: started
    enabled: yes