version: "3.9"

services:
  loki:
    image: grafana/loki:latest
    networks:
      - go-app
    ports:
      - "3100:3100"

  go-app:
    container_name: go-app
    build:
      context: .
      dockerfile: docker-setup/go-app/Dockerfile
    networks:
      - go-app
    depends_on:
      - loki
    ports:
      - 80:80
      - 9110:9110
    environment:
      LOKI_URL: "http://loki:3100"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "0"
    depends_on:
      - loki
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - go-app

networks:
  go-app:
    driver: bridge