global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter_docker'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.10.10:9100']

  - job_name: 'node_exporter_wordpress'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.5.10:9100']