global:
  scrape_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: "/metrics"
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'alertmanager'
    static_configs:
    - targets: ['localhost:9093']

  - job_name: 'wordpressNodeExporter'
    ec2_sd_configs: &ec2config
      - region: us-east-1
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: wordpress
        action: keep
        target_label: instance
  - job_name: 'wordpressMysqlExporter'
    ec2_sd_configs: *ec2config 
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: wordpress
        action: keep
        target_label: instance
      - source_labels: [__meta_ec2_private_ip]
        regex: '(.*)'
        replacement: '${1}:9104'
        target_label: __address__

  - job_name: 'dockerNodeExporter'
    ec2_sd_configs: *ec2config 
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: docker
        action: keep
        target_label: instance
  - job_name: 'dockerEngineExporter'
    ec2_sd_configs: *ec2config 
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: docker
        action: keep
        target_label: instance
      - source_labels: [__meta_ec2_private_ip]
        regex: '(.*)'
        replacement: '${1}:9323'
        target_label: __address__

