- name: Transfer main.tf file to home directory
  template:
    src: "{{ role_path }}/templates/main.tf.j2"
    dest: "/home/centos/main.tf"
    owner: centos
    group: centos
    mode: '0644'

- name: Copy siteExample file to home directory
  ansible.builtin.copy:
    src: "{{ role_path }}/files/siteExample"
    dest: "/home/centos/"
    owner: centos
    group: centos
    mode: '0755'

- name: Run Terraform
  ansible.builtin.shell:
    cmd: "cd /home/centos && terraform init && terraform apply -auto-approve"
  become: true