{
 "title": "AWS Lambda",
 "description": "Visualize AWS Lambda metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "1s,5s,10s,30s,1m,5m,15m,1h,6h,1d,7d,30d"
   },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "functionname",
    "label": "FunctionName",
    "query": "dimension_values($region,AWS/Lambda,Duration,FunctionName)"
   }
  ]
 },
 "panels": [
  { "title": "Data from JSON datasource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current running instances",
   "type": "table",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 1 },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "https://status-check-bucket.s3.amazonaws.com/health_check_output.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Custom metrics of lambda about instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Current running instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Status": "*" },
     "metricName": "InstanceStatus",
     "namespace": "CustomLambdaMetrics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Running instance count in time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 7 },
   "targets": [
    {
     "dimensions": { "Status": "*" },
     "metricName": "InstanceStatus",
     "namespace": "CustomLambdaMetrics",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Default metrics of lambda from CloudWatch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Lambda logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "fields @timestamp, @message |\n sort @timestamp desc ",
     "logGroups": [
      { "arn": "/aws/lambda/healthCheckLambda", "name": "/aws/lambda/healthCheckLambda" }
     ],
     "namespace": "AWS/Logs",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Invocations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Global Concurrent Executions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "UnreservedConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}