version: "3.9"

services:
  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    networks:
      - grafana
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "0"
    depends_on:
      - loki
    ports:
      - "3000:3000"
    volumes:
      - /home/centos/provisioning/datasources:/etc/grafana/provisioning/datasources/
      - /home/centos/provisioning/dashboards:/etc/grafana/provisioning/dashboards/
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      
    networks:
      - grafana

networks:
  grafana:
    driver: bridge