- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
  become: true
  notify: Start Docker containers

- name: Start Docker containers
  shell: "docker start `docker ps -q -l`"
  args:
    executable: /bin/bash
