- name: Copy main.tf folder to home directory
  ansible.builtin.copy:
    src: "{{ role_path }}/files/main.tf"
    dest: "/home/centos/main.tf"
    owner: centos
    group: centos
    mode: '0644'

- name: Copy siteExample folder to home directory
  ansible.builtin.copy:
    src: "{{ role_path }}/files/siteExample"
    dest: "/home/centos/"
    owner: centos
    group: centos
    mode: '0755'

- name: Run Terraform
  ansible.builtin.shell:
    cmd: "cd /home/centos && terraform init && terraform apply -auto-approve"
  become: true