- hosts: localhost
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3 

- hosts: ec2_wordpress
  vars:
    loki_url: "{{ hostvars[groups['ec2_loki_grafana'][0]]['network_interfaces'][0]['private_ip_address'] }}:3100"
    hostname: ec2_wordpress
  roles:
  - role: promtail
    when: loki_url is defined
  - server
  - php
  - mysql
  - wordpress
  - node-exporter
  - mysql-exporter