plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Name:
    - 'goApp'
    - 'loki-grafana'
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    prefix: ec2
    separator: "_"
