- name: Include mysql creds
  include_vars: "../../mysql/defaults/main.yml"

- name: Create /etc/mysql_exporter directory
  ansible.builtin.file:
    path: /etc/mysql_exporter
    state: directory
    mode: '0755'
  become: true

- name: Copy and fill template with MySQL creds
  ansible.builtin.template:
    src: "{{ role_path }}/templates/.my.cnf.j2"
    dest: /etc/mysql_exporter/.my.cnf
  become: true

- name: Execute SQL statement create user
  ignore_errors: true
  community.mysql.mysql_query:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    query: "CREATE USER {{ export_mysql_user }}@localhost IDENTIFIED BY '{{ export_mysql_password }}';"


- name: Grant access to new mysql user
  community.mysql.mysql_query:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    query: "GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO {{ export_mysql_user }}@'localhost';"


- name: Download Prometheus mysql Agent
  become: true
  get_url:
    url: "https://github.com/prometheus/mysqld_exporter/releases/download/v0.15.0/mysqld_exporter-0.15.0.linux-amd64.tar.gz"
    dest: "/tmp/mysqlAgent.tar.gz"

- name: Extract mysqlAgent Agent
  ansible.builtin.unarchive:
    src: "/tmp/mysqlAgent.tar.gz"
    dest: "/tmp/"
    remote_src: yes
  become: true

- name: Move node_exporter binary to /usr/bin
  shell: "mv /tmp/mysqld_exporter-*/mysqld_exporter /usr/bin/mysqld_exporter"
  args:
    executable: /bin/bash
  become: true

- name: Create Prometheus MySQL Agent user
  become: true
  user:
    name: "mysqld_exporter"
    system: yes
    shell: "/bin/false"

- name: Copy systemd service file
  become: true
  copy:
    src: "{{ role_path }}/files/mysql_exporter.service"
    dest: "/etc/systemd/system/mysql_exporter.service"

- name: Reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: Enable and start Prometheus Agent service
  become: true
  systemd:
    name: "mysql_exporter"
    state: started
    enabled: yes
