- hosts: all
  gather_facts: False

#tasks:
#- name: install python 2
#raw: test -e /usr/bin/python || (yum update -y && yum install -y python-minimal)

- hosts: all
  roles:
  - server
  - php
  - mysql
  - wordpress