- name: Install EPEL and Remi repositories
  yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: latest
    validate_certs: no
  become: true

- name: Enable Remi repository for PHP 8 on CentOS
  command: sudo yum install -y --enablerepo=remi-php80 php php-cli php-mysqlnd php-gd
  become: true

#- name: Install PHP MySQL extension and gd for PHP 8.0
#  yum:
#    name:
#      - php-mysql
#      - php-gd
#    state: latest
#    disable_gpg_check: yes  # Вимкніть перевірку GPG, якщо необхідно
#  become: true
