Vagrant.configure("2") do |config|
  #config.vm.provision "shell", inline: "??"
  #config.vm.provision "shell", path: "scriptGeneral.sh"
  #config.vm.provider "libvirt"


  config.vm.define "serv1" do |serv1|
    serv1.vm.box = "centos/7"
    serv1.vm.provision "file", source: "./fileSamples/index.html", destination: "~/index.html"
    serv1.vm.provision "file", source: "./fileSamples/nginxConf_serv1-host.conf", destination: "~/nginx.conf"
    serv1.vm.provision "shell", path: "scriptServ1-host.sh"

    serv1.vm.network 'private_network',
    ip: '192.168.1.10', netmask:'255.255.255.0'
  end

  config.vm.define "serv2" do |serv2|
    serv2.vm.box = "centos/7"
    serv2.vm.provision "file", source: "./fileSamples/nginxConf_serv2-redir.conf", destination: "~/nginx.conf"
    serv2.vm.provision "shell", path: "scriptServ2-redir.sh"
##
    

    serv2.vm.network 'private_network',
    ip: '192.168.2.10', netmask:'255.255.255.0'
  end
end
