datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-service-clusterip:9090
        access: proxy
        isDefault: true

adminUser: admin
adminPassword: admin
