Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.provider "virtualbox" do |vb|
        vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000]
      end
    config.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Kiev /etc/localtime", run: "always"
    
    config.vm.provision "file", source: "./files/prometheus.yml", destination: "~/prometheus.yml"
    config.vm.provision "file", source: "./files/prometheusService", destination: "~/prometheus.service"

    
    config.vm.provision "shell", path: "prometheusInstall.sh"
    config.vm.provision "shell", path: "prometheusInstall.sh"
    config.vm.network 'private_network',
    ip: '192.168.6.10', netmask:'255.255.255.0'
end
  

  