Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.provision "file", source: "./files/remote-server.cfg", destination: "~/remote-server.cfg"
    eonfig.vm.provision "shell", path: "nagiosInstall.sh"

    config.vm.network 'private_network',
    ip: '192.168.7.10', netmask:'255.255.255.0'
end
  

  