- name: Install NRPE and Nagios plugins
  become: true
  yum:
    name:
      - nrpe
      - wget
      - nagios-plugins-load
      - nagios-plugins-http
      - nagios-plugins-users
      - nagios-plugins-procs
      - nagios-plugins-disk
      - nagios-plugins-swap
      - nagios-plugins-nrpe
      - nagios-plugins-uptime
      - nagios-plugins-mysql
    state: present

- name:  Copy nrpe.cfg
  copy:
    src: "{{ role_path }}/files/nrpe.cfg"
    dest: /etc/nagios/nrpe.cfg
  become: true


- name: Enable NRPE service
  become: true
  systemd:
    name: nrpe
    enabled: yes
    state: restarted
