- name: Install NRPE and Nagios plugins
  become: true
  yum:
    name: "nrpe nagios-plugins-{load,http,users,procs,disk,swap,nrpe,uptime}"
    state: present

- name: Configure NRPE allowed hosts
  become: true
  lineinfile:
    path: "/etc/nagios/nrpe.cfg"
    line: "allowed_hosts=127.0.0.1,192.168.5.1"

- name: Enable NRPE service
  become: true
  systemd:
    name: nrpe
    enabled: yes
    state: restarted
