- name: Install NRPE and Nagios plugins
  become: true
  yum:
    name: "nrpe  wget nagios-plugins-{load,http,users,procs,disk,swap,nrpe,uptime,mysql}"
    state: present


- name:  Copy nrpe.cfg
  copy:
    src: "{{ role_path }}/files/nrpe.cfg"
    dest: /etc/nagios/nrpe.cfg
  become: true


- name: Enable NRPE service
  become: true
  systemd:
    name: nrpe
    enabled: yes
    state: restarted
