- name: Copy sourceCode to home directory
  ansible.builtin.copy:
    src: "{{ role_path }}/files/goAppSourceCode"
    dest: "/home/centos/"
    owner: centos
    group: centos
    mode: '0755'


- name: Build Go app docker container
  become: true
  command: 
    cmd:  docker build -t go-app-docker:latest -f Dockerfile.multistage .
    chdir: /home/centos/goAppSourceCode

- name: Run Go app docker container
  become: true
  command: 
    cmd: docker run --name go-app -p 80:80 -p 9110:9110 --restart=always -d go-app-docker
    chdir: /home/centos/goAppSourceCode
