- name: Install wget
  yum:
    name: wget
    state: present
  become: true

- name: Change to /tmp directory
  command: cd /tmp

- name: Download Go binary
  command: wget -O /tmp/goZip https://go.dev/dl/go1.21.5.linux-amd64.tar.gz

- name: Remove existing Go installation
  become: true
  command: rm -rf /usr/local/go

- name: Extract Go binary
  become: true
  command: tar -C /usr/local -xzf /tmp/goZip

- name: Set Go binary path in the environment
  become: true
  lineinfile:
    path: /etc/profile
    line: 'export PATH=$PATH:/usr/local/go/bin'

- name: Copy sourceCode to home directory
  ansible.builtin.copy:
    src: "{{ role_path }}/files/goAppSourceCode"
    dest: "/home/centos/"
    owner: centos
    group: centos
    mode: '0755'

- name: Build Go binary
  become: true
  command: 
    cmd: /usr/local/go/bin/go build -o /home/centos/app
    chdir: /home/centos/goAppSourceCode

- name: delete old files dir
  become: true
  command: rm -rf ./files

- name: Move files dir to home dir
  become: true
  command: mv -f ./goAppSourceCode/files ./

- name: Copy systemd service file of goApp
  become: true
  copy:
    src: "{{ role_path }}/files/goApp.service"
    dest: "/etc/systemd/system/goApp.service"

- name: Reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: Enable and start Prometheus Agent service
  become: true
  systemd:
    name: "goApp"
    state: started
    enabled: yes